#!/bin/sh
#
# Startup script for the Compute Node HA
#
# chkconfig: - 49 50
# description: This script starts Compute Node HA
# processname: computenodeha
# pidfile: /var/run/computenodeha.pid

# Source function library.
. /etc/rc.d/init.d/functions


computenodeha="/usr/bin/compute-node-ha"
[ -f ${computenodeha} ] || exit 0

OPTIONS="--config-file /etc/ComputeNodeHA/computeNodeHA.conf"

RETVAL=0

# See how we were called.
case "$1" in
  start)
        echo -n "Starting ComputeNodeHA: "
        $computenodeha $OPTIONS &
	    RETVAL=$?
        if [ $RETVAL -eq 0 ] ;then
		    success && touch /var/lock/subsys/computenodeha
        else
            failure
        fi
        echo
        ;;
  stop)

        echo -n "Shutting down ComputeNodeHA: "
        killproc compute-node-ha
	    RETVAL=$?
    
        if [ $RETVAL -eq 0 ];then
		    success
		    rm -f /var/lock/subsys/computenodeha /var/run/computenodeha.pid
        else
            failure
        fi
	echo
        ;;
  status)
	status compute-node-ha
	RETVAL=$?
	;;
  reload|condrestart|force-reload|restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|condrestart|status}"
        exit 2
esac

exit $RETVAL
